import { CountryShare, MatchFixture, MarketActivity, AppNotification } from './types';

const ALL_MOCK_COUNTRIES: CountryShare[] = [
  // Group A
  {
    id: 'QAT',
    name: 'Qatar',
    flag: '🇶🇦',
    rating: 3,
    currentPrice: 1.35,
    winningSettlementPrice: 180.00,
    potentialReturn: 74.1,
    group: 'A',
    ranking: 50,
    popularityScore: 70,
    trending: 'stable',
    change24h: 0.0,
    availableShares: 200000,
    totalSharesPurchased: 4500,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The passionate host nation of 2022, eager to shock the tournament as active contenders.'
  },
  {
    id: 'ECU',
    name: 'Ecuador',
    flag: '🇪🇨',
    rating: 3.5,
    currentPrice: 2.30,
    winningSettlementPrice: 100.00,
    potentialReturn: 43.5,
    group: 'A',
    ranking: 44,
    popularityScore: 75,
    trending: 'stable',
    change24h: 0.2,
    availableShares: 200000,
    totalSharesPurchased: 8200,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Known for high-altitude speed, tactical resilience, and explosive wing play.'
  },
  {
    id: 'SEN',
    name: 'Senegal',
    flag: '🇸🇳',
    rating: 4,
    currentPrice: 11.80,
    winningSettlementPrice: 110.00,
    potentialReturn: 9.3,
    group: 'A',
    ranking: 18,
    popularityScore: 82,
    trending: 'up',
    change24h: 1.5,
    availableShares: 250000,
    totalSharesPurchased: 18400,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The Lions of Teranga possess elite physical strength and top-tier African championship cohesion.'
  },
  {
    id: 'NED',
    name: 'Netherlands',
    flag: '🇳🇱',
    rating: 4.5,
    currentPrice: 19.50,
    winningSettlementPrice: 120.00,
    potentialReturn: 6.2,
    group: 'A',
    ranking: 7,
    popularityScore: 85,
    trending: 'stable',
    change24h: 0.5,
    availableShares: 300000,
    totalSharesPurchased: 31000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Masters of Total Football, combining technical brilliance, physical dominance, and solid defense.'
  },
  {
    id: 'SCO',
    name: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    rating: 3.5,
    currentPrice: 2.10,
    winningSettlementPrice: 100.00,
    potentialReturn: 47.6,
    group: 'A',
    ranking: 39,
    popularityScore: 71,
    trending: 'stable',
    change24h: 0.1,
    availableShares: 220000,
    totalSharesPurchased: 3500,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Resolute defensive lines combined with rapid physical transition attacks across the wings.'
  },
  {
    id: 'NGA',
    name: 'Nigeria',
    flag: '🇳🇬',
    rating: 4,
    currentPrice: 6.20,
    winningSettlementPrice: 110.00,
    potentialReturn: 17.7,
    group: 'A',
    ranking: 40,
    popularityScore: 83,
    trending: 'up',
    change24h: 0.7,
    availableShares: 250000,
    totalSharesPurchased: 9800,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The Super Eagles command incredible athletic speed, physical dominance, and prolific striker legacy.'
  },
  {
    id: 'NIR',
    name: 'Northern Ireland',
    flag: '🏴',
    rating: 3,
    currentPrice: 3.15,
    winningSettlementPrice: 100.00,
    potentialReturn: 31.7,
    group: 'A',
    ranking: 74,
    popularityScore: 68,
    trending: 'stable',
    change24h: 0.15,
    availableShares: 154000,
    totalSharesPurchased: 1200,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Defensive reliability combined with high strategic set-piece systems.'
  },

  // Group B
  {
    id: 'ENG',
    name: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    rating: 5,
    currentPrice: 20.10,
    winningSettlementPrice: 130.00,
    potentialReturn: 6.5,
    group: 'B',
    ranking: 4,
    popularityScore: 91,
    trending: 'stable',
    change24h: 0.8,
    availableShares: 410000,
    totalSharesPurchased: 85000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'A squad of Premier League stars hungry for international glory and backed by massive global support.'
  },
  {
    id: 'IRN',
    name: 'Iran',
    flag: '🇮🇷',
    rating: 3,
    currentPrice: 1.25,
    winningSettlementPrice: 90.00,
    potentialReturn: 72.0,
    group: 'B',
    ranking: 20,
    popularityScore: 68,
    trending: 'stable',
    change24h: 0.1,
    availableShares: 200000,
    totalSharesPurchased: 2100,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Highly disciplined defensive unit and a strong physical presence in Asian tournaments.'
  },
  {
    id: 'USA',
    name: 'United States',
    flag: '🇺🇸',
    rating: 3.5,
    currentPrice: 12.40,
    winningSettlementPrice: 200.00,
    potentialReturn: 8.1,
    group: 'B',
    ranking: 16,
    popularityScore: 88,
    trending: 'up',
    change24h: 2.4,
    availableShares: 350000,
    totalSharesPurchased: 48000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'A rapid, young squad with immense athletic capabilities and high investment upside.'
  },
  {
    id: 'WAL',
    name: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    rating: 3.5,
    currentPrice: 2.60,
    winningSettlementPrice: 100.00,
    potentialReturn: 38.5,
    group: 'B',
    ranking: 19,
    popularityScore: 72,
    trending: 'down',
    change24h: -0.4,
    availableShares: 200000,
    totalSharesPurchased: 5600,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Priding themselves on incredible national spirit, resolute defense, and direct free-kick power.'
  },
  {
    id: 'UKR',
    name: 'Ukraine',
    flag: '🇺🇦',
    rating: 3.5,
    currentPrice: 2.90,
    winningSettlementPrice: 100.00,
    potentialReturn: 34.5,
    group: 'B',
    ranking: 22,
    popularityScore: 75,
    trending: 'stable',
    change24h: 0.1,
    availableShares: 200000,
    totalSharesPurchased: 4000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Commanding high technical prowess in the central fields with strong wing crossers.'
  },
  {
    id: 'COL',
    name: 'Colombia',
    flag: '🇨🇴',
    rating: 4,
    currentPrice: 13.20,
    winningSettlementPrice: 115.00,
    potentialReturn: 8.7,
    group: 'B',
    ranking: 12,
    popularityScore: 84,
    trending: 'up',
    change24h: 0.9,
    availableShares: 230000,
    totalSharesPurchased: 12000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Spectacular South American flair, fierce counter-attacks, and a high-yield potential roster.'
  },
  {
    id: 'IRL',
    name: 'Ireland',
    flag: '🇮🇪',
    rating: 3.5,
    currentPrice: 4.90,
    winningSettlementPrice: 105.00,
    potentialReturn: 21.4,
    group: 'B',
    ranking: 60,
    popularityScore: 75,
    trending: 'stable',
    change24h: 0.25,
    availableShares: 210000,
    totalSharesPurchased: 2400,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Rugged physicality and rapid wing movements, known for high defensive efficiency.'
  },

  // Group C
  {
    id: 'ARG',
    name: 'Argentina',
    flag: '🇦🇷',
    rating: 5,
    currentPrice: 20.80,
    winningSettlementPrice: 150.00,
    potentialReturn: 7.2,
    group: 'C',
    ranking: 1,
    popularityScore: 97,
    trending: 'up',
    change24h: 4.8,
    availableShares: 320000,
    totalSharesPurchased: 125000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The reigning champions, led by legendary talent and an elite supporting midfield.'
  },
  {
    id: 'KSA',
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    rating: 3,
    currentPrice: 1.30,
    winningSettlementPrice: 90.00,
    potentialReturn: 69.2,
    group: 'C',
    ranking: 51,
    popularityScore: 74,
    trending: 'stable',
    change24h: -0.1,
    availableShares: 200000,
    totalSharesPurchased: 3100,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Renowned for tactical high defensive lines and shocking the world in tournament openers.'
  },
  {
    id: 'MEX',
    name: 'Mexico',
    flag: '🇲🇽',
    rating: 4,
    currentPrice: 4.80,
    winningSettlementPrice: 105.00,
    potentialReturn: 21.9,
    group: 'C',
    ranking: 15,
    popularityScore: 89,
    trending: 'stable',
    change24h: 0.3,
    availableShares: 280000,
    totalSharesPurchased: 24000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'A traditional knockout-stage contender with electric fan energy and highly fast winger attacks.'
  },
  {
    id: 'POL',
    name: 'Poland',
    flag: '🇵🇱',
    rating: 3.5,
    currentPrice: 5.90,
    winningSettlementPrice: 100.00,
    potentialReturn: 16.9,
    group: 'C',
    ranking: 26,
    popularityScore: 76,
    trending: 'stable',
    change24h: -0.2,
    availableShares: 210000,
    totalSharesPurchased: 9800,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Boasting historical strikers and highly organized defensive shields.'
  },
  {
    id: 'PER',
    name: 'Peru',
    flag: '🇵🇪',
    rating: 3.5,
    currentPrice: 3.60,
    winningSettlementPrice: 100.00,
    potentialReturn: 27.8,
    group: 'C',
    ranking: 35,
    popularityScore: 73,
    trending: 'stable',
    change24h: 0.0,
    availableShares: 190000,
    totalSharesPurchased: 4200,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Outstanding technical grit, famous for their high altitude dominance and loyal global support.'
  },
  {
    id: 'EGY',
    name: 'Egypt',
    flag: '🇪🇬',
    rating: 3.5,
    currentPrice: 1.85,
    winningSettlementPrice: 100.00,
    potentialReturn: 54.1,
    group: 'C',
    ranking: 36,
    popularityScore: 78,
    trending: 'up',
    change24h: 0.3,
    availableShares: 200000,
    totalSharesPurchased: 6500,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Armed with elite global wingers and defensive coordination capable of surprising top seeds.'
  },
  {
    id: 'HON',
    name: 'Honduras',
    flag: '🇭🇳',
    rating: 3,
    currentPrice: 1.80,
    winningSettlementPrice: 95.00,
    potentialReturn: 52.8,
    group: 'C',
    ranking: 78,
    popularityScore: 65,
    trending: 'stable',
    change24h: -0.1,
    availableShares: 120000,
    totalSharesPurchased: 800,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Renowned fast break systems with deep Central American footballing spirit.'
  },

  // Group D
  {
    id: 'FRA',
    name: 'France',
    flag: '🇫🇷',
    rating: 5,
    currentPrice: 20.95,
    winningSettlementPrice: 175.00,
    potentialReturn: 7.2,
    group: 'D',
    ranking: 2,
    popularityScore: 94,
    trending: 'up',
    change24h: 3.2,
    availableShares: 250000,
    totalSharesPurchased: 96000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The reigning powerhouse of Europe, France boasts an elite roster of world-class superstars.'
  },
  {
    id: 'AUS',
    name: 'Australia',
    flag: '🇦🇺',
    rating: 3,
    currentPrice: 4.20,
    winningSettlementPrice: 100.00,
    potentialReturn: 23.8,
    group: 'D',
    ranking: 38,
    popularityScore: 72,
    trending: 'up',
    change24h: 0.6,
    availableShares: 200000,
    totalSharesPurchased: 3300,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The Socceroos have incredible fighting spirit, tactical athleticism, and clinical set-pieces.'
  },
  {
    id: 'DEN',
    name: 'Denmark',
    flag: '🇩🇰',
    rating: 4,
    currentPrice: 10.90,
    winningSettlementPrice: 110.00,
    potentialReturn: 10.1,
    group: 'D',
    ranking: 10,
    popularityScore: 80,
    trending: 'stable',
    change24h: 0.4,
    availableShares: 240000,
    totalSharesPurchased: 14700,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'A highly cohesive team unit, Denmark blends technical wing-backs with creative midfield maestros.'
  },
  {
    id: 'TUN',
    name: 'Tunisia',
    flag: '🇹🇳',
    rating: 3,
    currentPrice: 1.55,
    winningSettlementPrice: 100.00,
    potentialReturn: 64.5,
    group: 'D',
    ranking: 30,
    popularityScore: 67,
    trending: 'stable',
    change24h: 0.1,
    availableShares: 180000,
    totalSharesPurchased: 1500,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Fiercely passionate and defensively rigid, making them extremely difficult to break down.'
  },
  {
    id: 'SWE',
    name: 'Sweden',
    flag: '🇸🇪',
    rating: 4,
    currentPrice: 8.10,
    winningSettlementPrice: 110.00,
    potentialReturn: 13.6,
    group: 'D',
    ranking: 23,
    popularityScore: 81,
    trending: 'stable',
    change24h: 0.2,
    availableShares: 220000,
    totalSharesPurchased: 7100,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'An physical, highly structured Scandinavian squad with strong wing crossing capabilities.'
  },
  {
    id: 'ALG',
    name: 'Algeria',
    flag: '🇩🇿',
    rating: 3.5,
    currentPrice: 3.20,
    winningSettlementPrice: 100.00,
    potentialReturn: 31.3,
    group: 'D',
    ranking: 34,
    popularityScore: 76,
    trending: 'stable',
    change24h: 0.0,
    availableShares: 190000,
    totalSharesPurchased: 2900,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The Desert Foxes bring immense individual technical brilliant flair and solid tactical shape.'
  },
  {
    id: 'BOL',
    name: 'Bolivia',
    flag: '🇧🇴',
    rating: 3,
    currentPrice: 1.50,
    winningSettlementPrice: 95.00,
    potentialReturn: 63.3,
    group: 'D',
    ranking: 81,
    popularityScore: 64,
    trending: 'stable',
    change24h: -0.15,
    availableShares: 130000,
    totalSharesPurchased: 950,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Excellent defensive coordination under extremely high athletic pressures.'
  },

  // Group E
  {
    id: 'ESP',
    name: 'Spain',
    flag: '🇪🇸',
    rating: 5,
    currentPrice: 19.95,
    winningSettlementPrice: 183.00,
    potentialReturn: 6.8,
    group: 'E',
    ranking: 8,
    popularityScore: 90,
    trending: 'stable',
    change24h: 1.1,
    availableShares: 300000,
    totalSharesPurchased: 54000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Masters of possession-based tiki-taka, passing opponents into utter exhaustion.'
  },
  {
    id: 'CRC',
    name: 'Costa Rica',
    flag: '🇨🇷',
    rating: 3,
    currentPrice: 1.20,
    winningSettlementPrice: 100.00,
    potentialReturn: 83.3,
    group: 'E',
    ranking: 31,
    popularityScore: 65,
    trending: 'stable',
    change24h: -0.3,
    availableShares: 170000,
    totalSharesPurchased: 900,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Renowned dark horses with outstanding goalkeeper legacy and tight counter blocks.'
  },
  {
    id: 'GER',
    name: 'Germany',
    flag: '🇩🇪',
    rating: 4.5,
    currentPrice: 19.65,
    winningSettlementPrice: 125.00,
    potentialReturn: 6.4,
    group: 'E',
    ranking: 11,
    popularityScore: 88,
    trending: 'down',
    change24h: -1.4,
    availableShares: 280000,
    totalSharesPurchased: 45000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'A clinical tournament nation combining ruthless efficiency, physical rigor, and technical poise.'
  },
  {
    id: 'JPN',
    name: 'Japan',
    flag: '🇯🇵',
    rating: 4,
    currentPrice: 8.95,
    winningSettlementPrice: 110.00,
    potentialReturn: 12.3,
    group: 'E',
    ranking: 24,
    popularityScore: 85,
    trending: 'up',
    change24h: 2.1,
    availableShares: 220000,
    totalSharesPurchased: 29000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Possess legendary lightning stamina, fast transition speeds, and deep team coordination.'
  },
  {
    id: 'AUT',
    name: 'Austria',
    flag: '🇦🇹',
    rating: 3.5,
    currentPrice: 6.80,
    winningSettlementPrice: 100.00,
    potentialReturn: 14.7,
    group: 'E',
    ranking: 25,
    popularityScore: 73,
    trending: 'stable',
    change24h: 0.1,
    availableShares: 190000,
    totalSharesPurchased: 3100,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'High-energy pressing squads, technically sound midfield pivots and sharp counter plays.'
  },
  {
    id: 'CHI',
    name: 'Chile',
    flag: '🇨🇱',
    rating: 3.5,
    currentPrice: 9.80,
    winningSettlementPrice: 100.00,
    potentialReturn: 10.2,
    group: 'E',
    ranking: 32,
    popularityScore: 76,
    trending: 'stable',
    change24h: -0.1,
    availableShares: 200000,
    totalSharesPurchased: 4500,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Fierce aggressive pressing counters, historical champions with premium tactical history.'
  },
  {
    id: 'PRY',
    name: 'Paraguay',
    flag: '🇵🇾',
    rating: 3.5,
    currentPrice: 5.70,
    winningSettlementPrice: 105.00,
    potentialReturn: 18.4,
    group: 'E',
    ranking: 56,
    popularityScore: 73,
    trending: 'stable',
    change24h: 0.0,
    availableShares: 165000,
    totalSharesPurchased: 1800,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Extremely tough defensive block backed by legendary South American grit.'
  },

  // Group F
  {
    id: 'BEL',
    name: 'Belgium',
    flag: '🇧🇪',
    rating: 4.5,
    currentPrice: 19.20,
    winningSettlementPrice: 120.00,
    potentialReturn: 6.3,
    group: 'F',
    ranking: 5,
    popularityScore: 84,
    trending: 'stable',
    change24h: -0.2,
    availableShares: 240000,
    totalSharesPurchased: 33000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'With a golden hierarchy of creative midfields and rapid transitions, Belgium is always a top threat.'
  },
  {
    id: 'CAN',
    name: 'Canada',
    flag: '🇨🇦',
    rating: 3.5,
    currentPrice: 1.40,
    winningSettlementPrice: 100.00,
    potentialReturn: 71.4,
    group: 'F',
    ranking: 41,
    popularityScore: 79,
    trending: 'up',
    change24h: 1.2,
    availableShares: 220000,
    totalSharesPurchased: 8900,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Boasting world-class pace on the wings and fearless athletic systems.'
  },
  {
    id: 'MOR',
    name: 'Morocco',
    flag: '🇲🇦',
    rating: 4.5,
    currentPrice: 15.90,
    winningSettlementPrice: 120.00,
    potentialReturn: 7.5,
    group: 'F',
    ranking: 11,
    popularityScore: 91,
    trending: 'up',
    change24h: 5.6,
    availableShares: 220000,
    totalSharesPurchased: 38000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'African powerhouse of defensive engineering, swift counters, and passionate fan bases.'
  },
  {
    id: 'CRO',
    name: 'Croatia',
    flag: '🇭🇷',
    rating: 4,
    currentPrice: 16.80,
    winningSettlementPrice: 120.00,
    potentialReturn: 7.1,
    group: 'F',
    ranking: 12,
    popularityScore: 83,
    trending: 'stable',
    change24h: 0.4,
    availableShares: 210000,
    totalSharesPurchased: 19500,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The absolute tournament masters of extra time, featuring legendary midfield composure and grit.'
  },
  {
    id: 'NOR',
    name: 'Norway',
    flag: '🇳🇴',
    rating: 4,
    currentPrice: 7.50,
    winningSettlementPrice: 115.00,
    potentialReturn: 15.3,
    group: 'F',
    ranking: 28,
    popularityScore: 82,
    trending: 'up',
    change24h: 1.1,
    availableShares: 210000,
    totalSharesPurchased: 8500,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Led by premium physical powerhouse strikers, Norway possesses incredible athletic directness.'
  },
  {
    id: 'TUR',
    name: 'Turkey',
    flag: '🇹🇷',
    rating: 4,
    currentPrice: 2.30,
    winningSettlementPrice: 110.00,
    potentialReturn: 47.8,
    group: 'F',
    ranking: 26,
    popularityScore: 80,
    trending: 'stable',
    change24h: 0.4,
    availableShares: 200000,
    totalSharesPurchased: 6200,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Vibrant mechanical midfield setups with a legendary passionate host crowd backing.'
  },
  {
    id: 'VEN',
    name: 'Venezuela',
    flag: '🇻🇪',
    rating: 3.5,
    currentPrice: 4.50,
    winningSettlementPrice: 105.00,
    potentialReturn: 23.3,
    group: 'F',
    ranking: 52,
    popularityScore: 72,
    trending: 'up',
    change24h: 0.35,
    availableShares: 145000,
    totalSharesPurchased: 1500,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Rapid physical wing counters fueled by solid national momentum.'
  },

  // Group G
  {
    id: 'BRA',
    name: 'Brazil',
    flag: '🇧🇷',
    rating: 5,
    currentPrice: 20.50,
    winningSettlementPrice: 150.00,
    potentialReturn: 7.3,
    group: 'G',
    ranking: 5,
    popularityScore: 95,
    trending: 'up',
    change24h: 2.5,
    availableShares: 500000,
    totalSharesPurchased: 112000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The historical favorite with five star decals, Brazil commands spectacular flair and pace.'
  },
  {
    id: 'SRB',
    name: 'Serbia',
    flag: '🇷🇸',
    rating: 3.5,
    currentPrice: 3.90,
    winningSettlementPrice: 100.00,
    potentialReturn: 25.6,
    group: 'G',
    ranking: 25,
    popularityScore: 74,
    trending: 'stable',
    change24h: 0.1,
    availableShares: 200000,
    totalSharesPurchased: 7600,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Imposing physical presence, outstanding crossing accuracy, and threat from corners.'
  },
  {
    id: 'SUI',
    name: 'Switzerland',
    flag: '🇨🇭',
    rating: 4,
    currentPrice: 14.50,
    winningSettlementPrice: 105.00,
    potentialReturn: 7.2,
    group: 'G',
    ranking: 15,
    popularityScore: 78,
    trending: 'stable',
    change24h: 0.3,
    availableShares: 220000,
    totalSharesPurchased: 11400,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Incredibly stable tournament competitors, famous for defensive solidity and midfield discipline.'
  },
  {
    id: 'CMR',
    name: 'Cameroon',
    flag: '🇨🇲',
    rating: 3,
    currentPrice: 1.65,
    winningSettlementPrice: 100.00,
    potentialReturn: 60.6,
    group: 'G',
    ranking: 43,
    popularityScore: 73,
    trending: 'up',
    change24h: 0.4,
    availableShares: 190000,
    totalSharesPurchased: 4100,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The Indomitable Lions bring power, flair, and high athletic ceiling to any challenge.'
  },
  {
    id: 'ITA',
    name: 'Italy',
    flag: '🇮🇹',
    rating: 4.5,
    currentPrice: 19.80,
    winningSettlementPrice: 135.00,
    potentialReturn: 6.8,
    group: 'G',
    ranking: 9,
    popularityScore: 89,
    trending: 'stable',
    change24h: 0.8,
    availableShares: 310000,
    totalSharesPurchased: 47000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Four-time champions with legendary defensive rigour and classic tournament composure.'
  },
  {
    id: 'CIV',
    name: 'Ivory Coast',
    flag: '🇨🇮',
    rating: 3.5,
    currentPrice: 5.10,
    winningSettlementPrice: 100.00,
    potentialReturn: 19.6,
    group: 'G',
    ranking: 38,
    popularityScore: 75,
    trending: 'up',
    change24h: 0.3,
    availableShares: 200000,
    totalSharesPurchased: 4800,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'The Elephants command outstanding central pivots and strong winger acceleration loops.'
  },
  {
    id: 'PAN',
    name: 'Panama',
    flag: '🇵🇦',
    rating: 3,
    currentPrice: 1.70,
    winningSettlementPrice: 100.00,
    potentialReturn: 58.8,
    group: 'G',
    ranking: 45,
    popularityScore: 68,
    trending: 'stable',
    change24h: 0.1,
    availableShares: 135000,
    totalSharesPurchased: 900,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Dynamic tactical cohesion and hard pressing lines in regional contests.'
  },

  // Group H
  {
    id: 'POR',
    name: 'Portugal',
    flag: '🇵🇹',
    rating: 5,
    currentPrice: 20.25,
    winningSettlementPrice: 140.00,
    potentialReturn: 6.9,
    group: 'H',
    ranking: 9,
    popularityScore: 89,
    trending: 'up',
    change24h: 1.9,
    availableShares: 340000,
    totalSharesPurchased: 65000,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Boasting athletic strikers and robust wingplay. Portugal represents premium investment potential.'
  },
  {
    id: 'GHA',
    name: 'Ghana',
    flag: '🇬🇭',
    rating: 3,
    currentPrice: 1.90,
    winningSettlementPrice: 100.00,
    potentialReturn: 52.6,
    group: 'H',
    ranking: 61,
    popularityScore: 75,
    trending: 'stable',
    change24h: -0.2,
    availableShares: 180000,
    totalSharesPurchased: 4800,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Incredible speed on counters, physical strength, and a rich tournament legacy.'
  },
  {
    id: 'URU',
    name: 'Uruguay',
    flag: '🇺🇾',
    rating: 4,
    currentPrice: 17.50,
    winningSettlementPrice: 115.00,
    potentialReturn: 6.6,
    group: 'H',
    ranking: 14,
    popularityScore: 81,
    trending: 'stable',
    change24h: 0.5,
    availableShares: 230000,
    totalSharesPurchased: 18900,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Combining legendary "Garra Charrúa" grit and physical dominance with top-tier strikers.'
  },
  {
    id: 'KOR',
    name: 'South Korea',
    flag: '🇰🇷',
    rating: 3.5,
    currentPrice: 5.50,
    winningSettlementPrice: 100.00,
    potentialReturn: 18.2,
    group: 'H',
    ranking: 28,
    popularityScore: 84,
    trending: 'up',
    change24h: 1.0,
    availableShares: 210000,
    totalSharesPurchased: 11200,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Led by elite world superstars, South Korea relies on incredible stamina and fast counters.'
  },
  {
    id: 'RSA',
    name: 'South Africa',
    flag: '🇿🇦',
    rating: 3,
    currentPrice: 1.75,
    winningSettlementPrice: 90.00,
    potentialReturn: 51.4,
    group: 'H',
    ranking: 55,
    popularityScore: 72,
    trending: 'stable',
    change24h: 0.0,
    availableShares: 180000,
    totalSharesPurchased: 2400,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Bafana Bafana brings rapid technical overlaps and outstanding home ground performance ratings.'
  },
  {
    id: 'NZL',
    name: 'New Zealand',
    flag: '🇳🇿',
    rating: 3,
    currentPrice: 1.45,
    winningSettlementPrice: 90.00,
    potentialReturn: 62.1,
    group: 'H',
    ranking: 84,
    popularityScore: 68,
    trending: 'stable',
    change24h: 0.1,
    availableShares: 170000,
    totalSharesPurchased: 1500,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Resilient defense, athletic set-piece strength, representing active Pacific contenders.'
  },
  {
    id: 'JAM',
    name: 'Jamaica',
    flag: '🇯🇲',
    rating: 3,
    currentPrice: 1.60,
    winningSettlementPrice: 100.00,
    potentialReturn: 62.5,
    group: 'H',
    ranking: 53,
    popularityScore: 70,
    trending: 'stable',
    change24h: 0.0,
    availableShares: 140000,
    totalSharesPurchased: 1100,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Electrifying explosive speed on counter maneuvers with incredible crowd power backing.'
  },
  {
    id: 'CUW',
    name: 'Curaçao',
    flag: '🇨🇼',
    rating: 3,
    currentPrice: 1.50,
    winningSettlementPrice: 100.00,
    potentialReturn: 66.7,
    group: 'D',
    ranking: 86,
    popularityScore: 65,
    trending: 'stable',
    change24h: 0.0,
    availableShares: 150000,
    totalSharesPurchased: 1200,
    status: 'ACTIVE',
    statistics: { wins: 0, draws: 0, losses: 0, goalsScored: 0, goalsConceded: 0, matchesPlayed: 0 },
    description: 'Caribbean flair combined with tactical defensive organization and rapid transition plays.'
  }
];

const BLACKLISTED_IDS: string[] = [];

export const INITIAL_COUNTRIES: CountryShare[] = ALL_MOCK_COUNTRIES.filter(
  c => !BLACKLISTED_IDS.includes(c.id)
);

export const INITIAL_FIXTURES: MatchFixture[] = [
  {
    id: 'm1',
    homeTeamId: 'CUW',
    awayTeamId: 'CIV',
    homeScore: null,
    awayScore: null,
    date: '2026-06-25',
    stage: 'Group Stage',
    status: 'Scheduled'
  },
  {
    id: 'm2',
    homeTeamId: 'TUN',
    awayTeamId: 'NED',
    homeScore: null,
    awayScore: null,
    date: '2026-06-26',
    stage: 'Group Stage',
    status: 'Scheduled'
  },
  {
    id: 'm3',
    homeTeamId: 'JPN',
    awayTeamId: 'SWE',
    homeScore: null,
    awayScore: null,
    date: '2026-06-27',
    stage: 'Group Stage',
    status: 'Scheduled'
  },
  {
    id: 'm4',
    homeTeamId: 'TUR',
    awayTeamId: 'USA',
    homeScore: null,
    awayScore: null,
    date: '2026-06-28',
    stage: 'Group Stage',
    status: 'Scheduled'
  }
];

export const INITIAL_ACTIVITIES: MarketActivity[] = [
  {
    id: 'act1',
    userName: '0x32df...54b1',
    countryId: 'BRA',
    countryName: 'Brazil',
    flag: '🇧🇷',
    amountInvested: 50.00,
    timestamp: '2 mins ago'
  },
  {
    id: 'act2',
    userName: 'Investor_US_99',
    countryId: 'USA',
    countryName: 'United States',
    flag: '🇺🇸',
    amountInvested: 100.00,
    timestamp: '5 mins ago'
  },
  {
    id: 'act3',
    userName: 'crypto_whale_9',
    countryId: 'ENG',
    countryName: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    amountInvested: 25.00,
    timestamp: '11 mins ago'
  },
  {
    id: 'act4',
    userName: '0x992a...110c',
    countryId: 'FRA',
    countryName: 'France',
    flag: '🇫🇷',
    amountInvested: 1500.00,
    timestamp: '15 mins ago'
  },
  {
    id: 'act5',
    userName: 'MessiFan_10',
    countryId: 'ARG',
    countryName: 'Argentina',
    flag: '🇦🇷',
    amountInvested: 250.00,
    timestamp: '22 mins ago'
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    title: 'Platform Launched!',
    message: 'Welcome to the inaugural FIFA World Cup Stock Shares platform. Begin owning high-yield country stocks.',
    type: 'info',
    timestamp: '10:15 AM',
    read: false
  },
  {
    id: 'n2',
    title: 'USA Stock Available at $2.20',
    message: 'United States shares are currently trading at $2.20 with a pre-set payout settlement of $100.00 if they win.',
    type: 'alert',
    timestamp: 'Yesterday',
    read: false
  }
];

export const MOCK_WALLET_ADDRESSES = {
  USDT: 'TYX8bB1HqA9vMybZ5UePr5aC1WqX8N3S9z',
  BTC: '3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy',
  ETH: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  BNB: 'bnb136ns6l086zlsdf84slfgsa0972g7al0s6szp2t'
};
